###
GET http://localhost:3003/api/blogs

###
POST http://localhost:3003/api/blogs
content-type: application/json

{
    "title": "hello",
    "author": "Testing",
    "url": "gg.com",
    "likes": 22
}

### Change id
PUT http://localhost:3003/api/blogs/60a218e10dba6d261798dc16
content-type: application/json

{
    "title": "hello",
    "author": "Testing",
    "url": "gg.com",
    "likes": 63
}

### Get users (This is not linked to the test DB)
GET http://localhost:3003/api/users


### posting test, checking username
POST http://localhost:3003/api/users
content-type: application/json

{
    "username": "hellas",
    "name": "Arto Hellas",
    "password": "testing2"
}

### posting test, checking username
POST http://localhost:3003/api/users
content-type: application/json

{
    "blogs": [],
    "username": "RuiHa",
    "name": "Rui Hachimura",
    "password": "juhjhkjhk"
}

### posting test, checking username
POST http://localhost:3003/api/users
content-type: application/json

{
    "blogs": [],
    "username": "Kawhi",
    "name": "Kawhi Leonard",
    "password": "asdf"
}


###
POST http://localhost:3003/api/blogs
content-type: application/json 

{
    "title": "Board man gets paid",
    "author": "Kawhi",
    "url": "tt@ll.com",
    "likes": "55",
    "userId": "60a7d9ecaf3d390f592fd879"
}

###
POST http://localhost:3003/api/blogs
content-type: application/json 

{
    "title": "what it do babyy",
    "author": "Kawhi",
    "url": "tt@ll.com",
    "likes": "55",
    "userId": "60a7d9ecaf3d390f592fd879"
}

###
POST http://localhost:3003/api/login
content-type: application/json 


{
    "username": "RuiHa",
    "password": "juhjhkjhk"
}

###
POST http://localhost:3003/api/login
content-type: application/json 


{
    "username": "Kawhi",
    "password": "asdf"
}

###
POST http://localhost:3003/api/blogs
content-type: application/json 
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IlJ1aUhhIiwiaWQiOiI2MGFiNWE4OGUxMTUxZjFkNTZiNDNlNDQiLCJpYXQiOjE2MjE4NDMxOTN9.8IfqT-Cc-f0y2pT1eveEg_MlE7vFzT_2m9cZ6tPJb60

{
    "title": "It's time to duel",
    "author": "Rui",
    "url": "tt@ll.com",
    "likes": "500",
    "userId": "60aa0c180d146e12af2842e0"
}

###
DELETE  http://localhost:3003/api/blogs/60abb194edf5c916b8c9931d
content-type: application/json 
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Ikthd2hpIiwiaWQiOiI2MGFiYjUyM2I2MzUyMTFjMDVmMTRmODQiLCJpYXQiOjE2MjE4NjU3ODl9.GFAipfDKpSZMkFlT2N3sZUMhHKetKnW3uO41mG-nux0
